### ISSUE TITLE
我遇到了您选择的风格不存在

### ISSUE THREAD

**Issue by Huelse** [Dreamer-Paul/Fantasy#3]
### 1. 该问题的重现步骤是什么？
启用或修改主题
### 2. 正常情况下应该是什么结果，你看到的呢？
外观更改成功
### 3. 服务器的运行环境是？

- 操作系统版本：虚拟云主机
- Apache/Nginx 版本：2.4
- PHP 版本：7.1
- 主题版本：beta
- 浏览器版本：chrome 70

[//]: # (如有图片请附上截图)
![图片](https://i.loli.net/2018/11/01/5bdaf809ce919.jpg)

**Comment by Dreamer-Paul** [comment]
你上传主题之后有没有重命名主题的文件夹？需要改成 `fantasy` 而不是 `fantasy-master`

同时你还得确认一下上传之后的文件权限是否分配正确，如果权限不足可能导致 Typecho 读取不到文件
