### ISSUE TITLE
为什么没有分类页面的入口？

### ISSUE THREAD

**Issue by ironmanic** [Dreamer-Paul/Fantasy#4]
怎么没有分类页面的入口？独立页面默认没有时间轴，要自己设计的吗？

**Comment by hifocus** [comment]
应该会在后续版本更新？ @Dreamer-Paul 醒醒，你 GitHub 都要长草了

**Comment by Dreamer-Paul** [comment]
哈哈，分类是默认显示在搜索里面的。原本我也想做一个二级菜单但是发现会影响那个动态效果，所以就取消了，现在更是直接变成了 `归档` 页面，不过 `归档` 页面目前是赞助功能，如果有需要的话你可以加入我的群联系我
